DROP TABLE HOSPITAL;
CREATE TABLE HOSPITAL(
    HOSNO NUMBER PRIMARY KEY,  -- 번호
    HOSNAME VARCHAR2(20 BYTE) NOT NULL,    -- 병원이름
    HOSPHONE CHAR(13 BYTE), -- 병원 전화번호
    ADDRESS VARCHAR2(100 BYTE), -- 병원 주소
    VACCINE_AMOUNT NUMBER DEFAULT 0  -- 백신 잔량
);

DROP SEQUENCE SEQ_HOSNO;
CREATE SEQUENCE SEQ_HOSNO
NOCACHE;

INSERT INTO HOSPITAL
VALUES(SEQ_HOSNO.NEXTVAL, '세브란스 병원', '02-2228-7170', '서울 신촌', 10);

INSERT INTO HOSPITAL
VALUES(SEQ_HOSNO.NEXTVAL, '서울대 병원', '1588-5700', '서울 혜화', 7);

INSERT INTO HOSPITAL
VALUES(SEQ_HOSNO.NEXTVAL, '아산 병원', '1688-7575', '서울 송파', DEFAULT);

INSERT INTO HOSPITAL
VALUES(SEQ_HOSNO.NEXTVAL, '인하대 병원', '032-890-2114', '인천', 3);

INSERT INTO HOSPITAL
VALUES(SEQ_HOSNO.NEXTVAL, '고대 안암 병원', '1577-0083', '서울 안암', 1);

COMMIT;

SELECT * FROM HOSPITAL;